### ISSUE TITLE
Requirements Document Final Draft

### ISSUE THREAD

**Issue by RickyV33** [RickyV33/Jama-Software#10]
Must give the requirements for the project and execution. Can be one of the recommendations given in the Requirements Document Skeleton ticket, or something of your own creation, just as long as it gives an overview of what needs to be done

Additional Assignee: Mike

**Comment by chances** [comment]
It should be fine for our MVP to just accept Jama credentials from the user. We shouldn't need to worry about rolling our own Auth system.

Credentials need to be stored these credentials in a session-dependent way.

* Does Express provide an easy way to store values in the session? With a plugin, perhaps?
* If not, flesh out requirements for our own storage scheme on the backend.
