### ISSUE TITLE
Mike Chally meeting to Review Requirements

### ISSUE THREAD

**Issue by RickyV33** [RickyV33/Jama-Software#14]
Scheduled for Wednesday, May 18 @ 2:30 PM
- what we would like to see in the vitalization of the data in Jama
- what kind of interactions we are looking for and what success looks like
- Both front end and back end

Questions for Jama:
- Auth: accept flat Jama credentials?
- Project selection, yeah?
- What kind of configuration? (Jama instance, etc.?)
- Licensing?

Additional Assignee: Mike
Requested by: Mike Chally

**Comment by chances** [comment]
Very productive meeting, all of the questions were answered and I took note of a lot of future goals/requirements for sprints after our initial.

**Concerning licensing:**

Default to the MIT license.

Mike C and Jama will hammer out a more specific license for the future with their team and lawyers. We can go ahead and just sticker on the MIT license for now.
