### ISSUE TITLE
Create Submit function requesting authentication from Jama

### ISSUE THREAD

**Issue by kathtran** [RickyV33/Jama-Software#39]
1. Send captured username and password to Jama server for authentication

2. Initialize VALID_LOGIN and INVALID_LOGIN messages

VALID_LOGIN: "Welcome to Jama."
INVALID_LOGIN: "Error: Incorrect username and/or password, please try again."

3. On valid login credentials: Store valid credentials in the session, per #40.
Display WELCOME message to user before account is displayed.
Capture JSON from Jama with list of projects for user.
Send JSON to User_Projects_Display function.

4. (ERROR) Invalid login credentials: Display pop-up window with "INVALID_USERNAME_AND_PASSWORD_COMBINATION."
Clear stored username and password.
Clear username and password form fields.

**Comment by chances** [comment]
Why was this closed?

**Comment by RickyV33** [comment]
Looks like Kathleen made a new one with an updated description
