### ISSUE TITLE
Create 'projects' endpoint

### ISSUE THREAD

**Issue by kathtran** [RickyV33/Jama-Software#53]
As a user, I want a 'projects' route so that I can select a project to visualize.

Create a '/projects' route endpoint in the backend to handle project related requests.

The GET controller method:

[1] Gather the user's projects
[2] Renders a projects view

**Comment by ruv-prog-so** [comment]
Can someone elaborate on this ticket? Both the projects get method and the ejs file were created in the previous sprint. Do we just do the testing for this get controller?

**Comment by chances** [comment]
#54, #55, and #56 are dependencies on this story. They'll have to be fully completed and tested first. Then, any additional tests that need to be written for this story can be created.

**Comment by chances** [comment]
See the [Gather/Display User Projects label](https://github.com/RickyV33/Jama-Software/issues?utf8=%E2%9C%93&q=label%3A%22Gather%2FDisplay%20User%20Projects%22%20)

**Comment by ibilal** [comment]
The Projects List View is ready for review. You guys can take a look at it and let us know if you need anything else for this story.
