### ISSUE TITLE
Test Pagination.js

### ISSUE THREAD

**Issue by RickyV33** [RickyV33/Jama-Software#69]
Test the promise that is returned
try variation of all the arguments being passed in being invalid/valid

**Comment by chances** [comment]
Will have to stub out the third-party `request` here using [proxyquire](https://www.npmjs.com/package/proxyquire), too?

**Comment by RickyV33** [comment]
Dang, that's right. we're going to have to.

**Comment by chances** [comment]
Oh, geez. The stub is going to have to mimick some sort basic

**Comment by ibilal** [comment]
is the proxyquire something that you guys did last night?

**Comment by RickyV33** [comment]
I added it in this morning, but it's something we realized we needed last night in order to test request(...) in pagination. Not everyone who runs this test will have the same username/password for their accounts, so you can stub out the request and have it return a response on a certain username/password combo and error on others.

**Comment by chances** [comment]
It's also to help ensure that our unit tests only test the single unit on its own. We don't want our unit tests depending on however some external system operates. (i.e. The pagination module shouldn't depend on the real implementation of the request module.)
