### ISSUE TITLE
Project Plan Final Draft

### ISSUE THREAD

**Issue by RickyV33** [RickyV33/Jama-Software#9]
Project plan should be have direction and everything should be planned out. This includes implementation, validation, verification. Make sure to include we'll be doing agile development.

May include the following:
*  scope and objectives of the project 
* deliverables the project will produce 
* process which shall be employed to produce those deliverables 
* time frame and milestones for the production of the deliverables 
*  organization and staffing which will be established 
* responsibilities of those involved 
* work steps to be undertaken 
* budget 

Additional Assignee: Kathleen

**Comment by ruv-prog-so** [comment]
So this is a general Project plan and not an iteration Project Plan?

**Comment by RickyV33** [comment]
@ruv-prog-so Right. I've updated the post to show what it may include.
